---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates a static website and backend AWS services for the AWS Elemental Media Services VOD workshop

Resources:

  MediaConvertIAMandS3:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      #Parameters:
      #  MediaBucketName: !Sub "${AWS::StackName}"
      TemplateURL: https://s3.amazonaws.com/rodeolabz-us-west-2/vodconsole/cf/MediaConvertIAMandS3.yaml
      TimeoutInMinutes: 60
    
Outputs:
  MediaBucketName:
    Value: !GetAtt MediaConvertIAMandS3.Outputs.MediaBucket
  MediaConvertRole:
    Value: !GetAtt MediaConvertIAMandS3.Outputs.MediaConvertRole
