---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates a static website and backend AWS services for the AWS Elemental Media Services VOD workshop

Resources:

  MediaConvertIAMandS3:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      #Parameters:
      #  MediaBucketName: !Sub "${AWS::StackName}"
      TemplateURL: https://s3.amazonaws.com/rodeolabz-us-west-2/vodconsole/cf/MediaConvertIAMandS3.yaml
      TimeoutInMinutes: 60
  WatchFolder:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
      Parameters:
        MediaBucket: !GetAtt MediaConvertIAMandS3.Outputs.MediaBucket
        MediaConvertRoleArn: !GetAtt MediaConvertIAMandS3.Outputs.MediaConvertRoleArn
      TemplateURL: https://s3.amazonaws.com/rodeolabz-us-west-2/vodconsole/cf/WatchFolder.yaml
      TimeoutInMinutes: 60
    
Outputs:
  MediaBucketName:
    Value: !GetAtt MediaConvertIAMandS3.Outputs.MediaBucket
  MediaConvertRole:
    Value: !GetAtt MediaConvertIAMandS3.Outputs.MediaConvertRole
  MediaConvertRoleArn:
    Value: !GetAtt MediaConvertIAMandS3.Outputs.MediaConvertRoleArn 
  WatchFolderBucketName:
    Value: !GetAtt WatchFolder.Outputs.WatchFolderBucket     
  LambdaRoleArn:
    Value: !GetAtt WatchFolder.Outputs.LambdaRoleArn
